"use client"

import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'it' | 'en'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const translations = {
  it: {
    // Common
    'common.welcome': 'Benvenuto',
    'common.login': 'Accedi',
    'common.register': 'Registrati',
    'common.logout': 'Esci',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.name': 'Nome',
    'common.save': 'Salva',
    'common.cancel': 'Annulla',
    'common.delete': 'Elimina',
    'common.edit': 'Modifica',
    'common.search': 'Cerca',
    'common.loading': 'Caricamento...',
    'common.settings': 'Impostazioni',
    'common.toggleLanguage': 'Cambia lingua',
    'common.myAccount': 'Il mio account',
    'common.profile': 'Profilo',
    
    // Login
    'login.identifierPlaceholder': 'nome@esempio.com o nickname',
    'login.passwordPlaceholder': '••••••••',

    // Standalone Login/Register pages
    'auth.login.title': 'Entra su Vybes',
    'auth.login.subtitle': 'Gestisci account, notifiche, annunci e molto altro.',
    'auth.login.emailLabel': 'E-mail',
    'auth.login.emailPlaceholder': 'Inserisci la tua email',
    'auth.login.passwordLabel': 'Password',
    'auth.login.passwordPlaceholder': 'Inserisci la tua password',
    'auth.login.forgotPassword': 'Hai dimenticato la password?',
    'auth.login.identifierLabel': 'E-mail o Nickname',
    'auth.login.submitting': 'Accesso in corso...',
    'auth.login.submit': 'ACCEDI',
    'auth.login.noAccount': 'Non hai ancora un account?',
    'auth.login.goRegister': 'REGISTRATI',

    'auth.register.title': 'Crea il tuo account',
    'auth.register.subtitle': 'Unisciti alla community artistica',
    'auth.register.nameLabel': 'Nome',
    'auth.register.namePlaceholder': 'Il tuo nome',
    'auth.register.emailLabel': 'E-mail',
    'auth.register.emailPlaceholder': 'nome@esempio.com',
    'auth.register.roleLabel': 'Ruolo',
    'auth.register.role.viewer': 'Visualizzatore',
    'auth.register.role.artist': 'Artista',
    'auth.register.role.recruiter': 'Recruiter',
    'auth.register.passwordLabel': 'Password',
    'auth.register.passwordConfirmLabel': 'Conferma Password',
    'auth.register.passwordPlaceholder': 'Inserisci una password sicura',
    'auth.register.confirmPasswordPlaceholder': 'Conferma la password',
    'auth.register.submitting': 'Registrazione in corso...',
    'auth.register.submit': 'REGISTRATI',

    // Auth page (single entrypoint)
    'auth.hero.description': "Unisciti alla community più vibrante. Connetti artisti, recruiter e appassionati d'arte in un'unica piattaforma.",
    'auth.feature.portfolio': 'Portfolio',
    'auth.feature.map': 'Mappa',
    'auth.feature.chat': 'Chat',
    'auth.feature.gamification': 'Gamification',
    'auth.cta.login': 'Accedi',
    'auth.cta.register': 'Registrati',
    'auth.stats.artists': 'Artisti',
    'auth.stats.events': 'Eventi',
    'auth.stats.recruiters': 'Recruiter',
    'auth.stats.cities': 'Città',
    
    // Landing
    'landing.hero.title': 'La Piattaforma per la Cultura Artistica',
    'landing.hero.subtitle': 'Connetti artisti, recruiter e appassionati in un unico spazio creativo',
    'landing.hero.cta': 'Inizia ora',
    'landing.hero.slogan.are': 'SEI',
    'landing.hero.slogan.you': 'PRONTO',
    'landing.hero.slogan.readyToMakeSome': 'A FARE UN PO’ DI',
    'landing.hero.slogan.noise': 'RUMORE',
    'landing.hero.cta.letsGo': 'Let’s go!',
    'landing.loginAttempt.title': 'Tentativo di login',
    'landing.loginAttempt.desc': 'Verifica delle credenziali...',
    'landing.login.title': 'Entra su Vybes',
    'landing.login.subtitle': 'Gestisci account, notifiche, annunci e molto altro.',
    'landing.login.emailLabel': 'E-mail',
    'landing.login.emailPlaceholder': 'nome@esempio.com',
    'landing.login.passwordLabel': 'Password',
    'landing.login.passwordPlaceholder': 'Inserisci la tua password',
    'landing.login.forgotPassword': 'Hai dimenticato la password?',
    'landing.login.submit': 'ACCEDI',
    'landing.login.submitting': 'Accesso in corso...',
    'landing.login.noAccount': 'Non hai ancora un account?',
    'landing.login.goRegister': 'REGISTRATI',
    'landing.register.roles.title': 'Quali ruoli vuoi assumere?',
    'landing.register.roles.subtitle': 'Puoi selezionare uno o entrambi i ruoli.',
    'landing.register.role.artist': 'Artista',
    'landing.register.role.recruiter': 'Recruiter',
    'landing.register.selected': 'Hai selezionato:',
    'landing.register.selected.artist': '🎤 Artista',
    'landing.register.selected.recruiter': '🎭 Recruiter',
    'landing.register.field.firstName': 'Nome',
    'landing.register.field.lastName': 'Cognome',
    'landing.register.field.birthDate': 'Data di nascita',
    'landing.register.field.email': 'Email',
    'landing.register.field.emailConfirm': 'Conferma Email',
    'landing.register.field.username': 'Username',
    'landing.register.field.password': 'Password',
    'landing.register.field.passwordConfirm': 'Conferma Password',
    'landing.register.field.artistName': 'Nome d’arte',
    'landing.register.field.recruiterType': 'Tipo di recruiter',
    'landing.register.recruiterType.placeholder': 'Seleziona tipo...',
    'landing.register.recruiterType.private': 'Privato',
    'landing.register.recruiterType.company': 'Azienda',
    'landing.register.submit': 'REGISTRATI',
    'landing.register.submitting': 'Registrazione in corso...',
    'landing.register.backToLogin': '← Torna al login',

    // Validation (Landing register)
    'validation.firstNameRequired': 'Nome obbligatorio.',
    'validation.lastNameRequired': 'Cognome obbligatorio.',
    'validation.birthDateRequired': 'Data di nascita obbligatoria.',
    'validation.emailRequired': 'Email obbligatoria e conferma necessaria.',
    'validation.emailsMismatch': 'Le email non coincidono.',
    'validation.usernameRequired': 'Username obbligatorio.',
    'validation.usernameInvalid': 'Username non valido.',
    'validation.passwordRequired': 'Password obbligatoria e conferma necessaria.',
    'validation.passwordsMismatch': 'Le password non coincidono.',
    'validation.passwordTooShort': 'Password troppo corta.',
    'validation.roleRequired': 'Seleziona almeno un ruolo.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.feed': 'Feed',
    'dashboard.map': 'Mappa',
    'dashboard.profile': 'Profilo',
    'dashboard.events': 'Eventi',
    'dashboard.messages': 'Messaggi',
    'dashboard.portfolio': 'Portfolio',
    'dashboard.quests': 'Missioni',
    'dashboard.minigames': 'Minigames',
    
    // Events
    'events.title': 'Eventi',
    'events.create': 'Crea Evento',
    'events.upcoming': 'Prossimi',
    'events.active': 'In Corso',
    'events.completed': 'Completati',
    'events.saved': 'Salvati',
    
    // Profile
    'profile.level': 'Livello',
    'profile.reputation': 'Reputazione',
    'profile.experience': 'Esperienza',
    'profile.followers': 'Seguaci',
    'profile.following': 'Seguiti',
    
    // Settings
    'settings.title': 'Impostazioni',
    'settings.description': 'Gestisci le tue preferenze e configurazioni',
    'settings.profile.title': 'Informazioni Profilo',
    'settings.profile.description': 'Modifica le tue informazioni personali e anagrafiche',
    'settings.profile.name': 'Nome Completo',
    'settings.profile.username': 'Username',
    'settings.profile.email': 'Email',
    'settings.profile.emailNote': 'L\'email non può essere modificata',
    'settings.profile.bio': 'Bio',
    'settings.profile.bioPlaceholder': 'Racconta qualcosa di te...',
    'settings.profile.location': 'Posizione',
    'settings.profile.locationPlaceholder': 'La tua città o paese',
    'settings.profile.website': 'Sito Web / Link',
    'settings.profile.websitePlaceholder': 'https://...',
    'settings.profile.websiteNote': 'Link al tuo sito web, portfolio o social',
    'settings.profile.uploadImage': 'Carica Immagine',
    'settings.profile.save': 'Salva Modifiche',
    'settings.profile.saving': 'Salvataggio...',
    'settings.profile.imageTypes': 'JPG, PNG o GIF. Max 5MB',
    'settings.appearance.title': 'Aspetto',
    'settings.appearance.description': 'Personalizza l\'aspetto dell\'applicazione',
    'settings.appearance.theme': 'Tema',
    'settings.appearance.themeDesc': 'Cambia tra tema chiaro e scuro',
    'settings.appearance.language': 'Lingua',
    'settings.appearance.languageDesc': 'Seleziona la lingua dell\'interfaccia',
    'settings.notifications.title': 'Notifiche',
    'settings.notifications.description': 'Gestisci le tue preferenze di notifica',
    'settings.notifications.email': 'Notifiche Email',
    'settings.notifications.emailDesc': 'Ricevi notifiche via email',
    'settings.notifications.push': 'Notifiche Push',
    'settings.notifications.pushDesc': 'Ricevi notifiche push nel browser',
    'notifications.markAllRead': 'Segna tutte come lette',
    'notifications.empty': 'Nessuna notifica',
    'notifications.viewAll': 'Vedi tutte le notifiche',
    'settings.account.title': 'Account',
    'settings.account.description': 'Gestisci le informazioni del tuo account',
    'settings.account.changePassword': 'Cambia Password',
    'settings.account.deleteAccount': 'Elimina Account',
    'settings.roles.title': 'Gestione Ruoli',
    'settings.roles.description': 'Aggiungi o rimuovi ruoli dal tuo account',
    'settings.roles.artist': 'Artista',
    'settings.roles.recruiter': 'Recruiter',
    'settings.roles.addArtist': '+ Aggiungi Artista',
    'settings.roles.addRecruiter': '+ Aggiungi Recruiter',
    'settings.roles.active': 'Ruoli attivi',
    
    // Profile
    'profile.edit': 'Modifica Profilo',
    'profile.edit.subtitle': 'Aggiorna le tue informazioni personali',
    'profile.edit.uploadHint': "Clicca sull'icona per caricare una nuova immagine",
    'profile.edit.profileLinkHint': 'Usato per il tuo link profilo:',
    'profile.follow': 'Segui',
    'profile.unfollow': 'Non seguire più',
    'profile.stats': 'Statistiche',
    'profile.portfolio': 'Portfolio',
    'profile.portfolio.empty': 'Il portfolio è vuoto',
    'profile.portfolio.addFirst': 'Aggiungi la tua prima opera',
    'profile.portfolio.add': 'Aggiungi Opera',
    'profile.events.title': 'I Miei Eventi',
    'profile.events.description': 'Gestisci i tuoi eventi e partecipazioni',
    'profile.events.create': 'Crea Evento',
    'profile.events.completed': 'Completati',
    'profile.events.ongoing': 'In Corso',
    'profile.events.saved': 'Salvati',
    'profile.events.created': 'Creati',
    'profile.avatar.title': 'Personalizza Avatar',
    'profile.avatar.description': 'Personalizza il tuo avatar 3D con outfit e accessori',
    'profile.avatar.open': 'Apri Fitting Room',
    
    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.description': 'Mostra la tua arte al mondo',
    'portfolio.add': 'Aggiungi Opera',
    'portfolio.empty': 'Il tuo portfolio è vuoto',
    'portfolio.loading': 'Caricamento portfolio...',
    'portfolio.onlyArtists': 'Questa sezione è disponibile solo per gli artisti',
    'portfolio.create.title': 'Aggiungi al Portfolio',
    'portfolio.create.subtitle': "Condividi le tue opere d'arte con la community",
    'portfolio.create.fileUploadError': 'Errore nel caricamento del file',
    'portfolio.create.createError': 'Errore nella creazione del portfolio item',
    'portfolio.create.retry': 'Errore nella creazione del portfolio item. Riprova.',
    'portfolio.create.onlyArtists': 'Solo gli artisti possono aggiungere al portfolio',
    'portfolio.create.back': 'Indietro',
    'portfolio.create.titleLabel': 'Titolo',
    'portfolio.create.titlePlaceholder': "Titolo dell'opera",
    'portfolio.create.descriptionLabel': 'Descrizione',
    'portfolio.create.descriptionPlaceholder': 'Descrivi la tua opera...',
    'portfolio.create.typeLabel': 'Tipo',
    
    // Events
    'events.loading': 'Caricamento eventi...',
    'events.noCompleted': 'Nessun evento completato',
    'events.noOngoing': 'Nessun evento in corso',
    'events.noSaved': 'Nessun evento salvato',
    'events.noCreated': 'Nessun evento creato',
    'events.participants': 'partecipanti',
    
    // Common placeholders
    'placeholder.search': 'Cerca utenti, post, eventi...',
    'placeholder.comment': 'Scrivi un commento...',
    'placeholder.post': 'Cosa vuoi condividere?',
    'placeholder.searchMap': 'Cerca artista, città, opportunità...',
    'placeholder.title': 'Titolo',
    'placeholder.description': 'Descrizione',
    'placeholder.city': 'Città',
    'placeholder.location': 'Luogo o indirizzo',
    'placeholder.latitude': 'Latitudine',
    'placeholder.longitude': 'Longitudine',
    
    // Toast messages
    'toast.success': 'Successo',
    'toast.error': 'Errore',
    'toast.emailVerified': 'Email verificata',
    'toast.emailVerifiedDesc': 'Ora puoi accedere al tuo account',
    'toast.verifyError': 'Errore verifica',
    'toast.invalidToken': 'Token di verifica non valido',
    'toast.expiredToken': 'Token di verifica scaduto',
    'toast.verifyGenericError': 'Errore durante la verifica',
    'toast.eventCreated': 'Evento creato con successo',
    'toast.eventCreateError': 'Errore nella creazione dell\'evento',
    'toast.markerCreated': 'Marker creato con successo',
    'toast.markerCreateError': 'Errore nella creazione del marker',
    'toast.profileUpdated': 'Profilo aggiornato con successo',
    'toast.profileUpdateError': 'Errore nell\'aggiornamento del profilo',
    'toast.roleAdded': 'Ruolo aggiunto',
    'toast.roleAddedDesc': 'Ruolo aggiunto con successo',
    'toast.loading': 'Caricamento...',
    'toast.imageUploaded': 'Immagine caricata',
    'toast.imageUploadSuccess': 'L\'immagine è stata caricata con successo',
    'toast.imageUploadError': 'Errore nel caricamento dell\'immagine',
    'toast.imageTypeError': 'Il file deve essere un\'immagine',
    'toast.imageSizeError': 'L\'immagine non deve superare 5MB',
    'toast.roleAddError': 'Errore nell\'aggiunta del ruolo',
    'toast.loginSuccess': 'Login riuscito',
    'toast.loginError': 'Errore login',
    'toast.genericError': 'Errore generale',
    'toast.validationError': 'Errore validazione',
    'toast.serverError': 'Errore server',
    'toast.registrationAttempt': 'Tentativo di registrazione',
    'toast.registrationSuccess': 'Registrazione completata',
    'toast.registrationError': 'Errore nella registrazione',
    'toast.purchaseSuccess': 'Acquisto completato',
    'toast.purchaseError': 'Errore acquisto',
    'toast.avatarSaved': 'Avatar salvato',
    'toast.avatarError': 'Errore nel salvataggio dell\'avatar',
    'toast.quizCompleted': 'Quiz completato!',
    'toast.loginRedirect': 'Reindirizzamento alla dashboard...',
    'toast.invalidCredentials': 'Email o password non corretti, oppure email non verificata',
    'toast.registrationSending': 'Invio dei dati al server...',
    'toast.checkEmail': 'Controlla la tua email per confermare l\'account',
    'toast.passwordMismatch': 'Le password non corrispondono',
    'toast.passwordTooShort': 'La password deve essere di almeno 8 caratteri',
    'toast.validationOk': 'Validazione OK',
    'toast.formValid': 'Form valido, invio richiesta...',
    'toast.wheelError': 'Errore nel girare la ruota',
    'toast.wheelWarning': 'Attenzione',
    'toast.quizUnlockOutfit': 'Hai sbloccato un nuovo outfit nel fitting room!',
    'toast.avatarConfigSaved': 'La configurazione del tuo avatar è stata salvata',
    'toast.avatarSaveError': 'Errore durante il salvataggio',
    
    // Avatar
    'avatar.itemNotOwned': 'Devi acquistare questo oggetto prima di usarlo',
    'avatar.category.face': 'Faccia',
    'avatar.category.eyes': 'Occhi',
    'avatar.category.hair': 'Capelli',
    'avatar.category.top': 'Busto',
    'avatar.category.bottom': 'Pantaloni',
    'avatar.category.accessories': 'Accessori',
    'avatar.previewTitle': 'Anteprima Avatar',
    'avatar.preview3d': 'Preview Avatar 3D',
    'avatar.preview3dNote': '(Render 3D da implementare)',
    'avatar.useAvatarInstead': 'Usa Avatar invece di immagine profilo',
    'avatar.saving': 'Salvataggio...',
    'avatar.saveConfig': 'Salva Configurazione',
    'avatar.customizeTitle': 'Personalizza Avatar',
    'avatar.currentlySelected': 'Attualmente selezionato',
    'common.active': 'Attivo',
    'common.inactive': 'Inattivo',
    'toast.itemNotOwned': 'Item non posseduto',
    'avatar.purchaseSuccess': 'Acquisto completato',
    'avatar.purchaseSuccessDesc': 'Oggetto acquistato con successo!',
    'avatar.purchaseError': 'Errore durante l\'acquisto',
    
    // Map
    'map.loading': 'Caricamento mappa...',
    'map.newAnnouncement': 'Nuovo Annuncio',
    'map.newMarker': 'Nuovo Marker',
    'map.newMarkerShort': 'Nuovo',
    'map.artists': 'Artisti',
    'map.opportunities': 'Opportunità',
    'map.all': 'Tutti',
    'map.new': 'Nuovo',
    'map.search': 'Cerca',
    'map.filter': 'Filtra',
    'map.filter.artists': 'Artisti',
    'map.filter.opportunity': 'Opportunità',
    'map.createAnnouncement': 'Crea Annuncio',
    'map.opportunity': 'Opportunità',
    'map.collaboration': 'Collaborazione',
    'map.clickToAdd': 'Clicca sulla mappa per aggiungere un marker',
    'map.searchPlace': 'Cerca un luogo',
    'map.selectPlace': 'Seleziona un luogo dalla ricerca',
    'map.selectLocation': 'Luogo selezionato',
    'map.latitude': 'Latitudine',
    'map.longitude': 'Longitudine',
    'map.candidate': 'Candidati',
    'map.contact': 'Contatta',
    'map.organizer': 'Organizzatore',
    'map.noResults': 'Nessun risultato trovato',
    'map.enterLocation': 'Inserisci un luogo',
    'map.detail.apply': 'Candidati',
    'map.detail.contact': 'Contatta',
    'map.searchPlaceholder': 'Cerca luogo, città, artista...',
    'map.marker.typeOpportunity': 'Opportunità',
    'map.marker.typeCollaboration': 'Collaborazione',
    'map.marker.create': 'Crea Marker',
    
    // Search
    'search.users': 'Utenti',
    'search.posts': 'Post',
    'search.events': 'Eventi',
    'search.user': 'Utente',
    'search.noResults': 'Nessun risultato trovato',
    'search.loading': 'Caricamento...',
    'search.like': 'like',
    'search.comments': 'commenti',

    // Feed
    'feed.comments.empty': 'Nessun commento ancora. Sii il primo a commentare!',
    'feed.newPost.title': 'Nuovo Post',
    'feed.newPost.fileLabel': 'File',
    'feed.newPost.tags': 'Tag',
    'feed.newPost.cancel': 'Annulla',
    'feed.newPost.publish': 'Pubblica',
    'feed.newPost.publishing': 'Pubblicazione...',
    'feed.newPost.uploadError': 'Errore nel caricamento del file',
    'feed.newPost.retry': 'Errore nella pubblicazione del post. Riprova.',

    // Collaboration post
    'collab.title': 'Crea Collaborazione',
    'collab.descriptionLabel': 'Descrizione Collaborazione',
    'collab.descriptionPlaceholder': 'Descrivi la collaborazione che vuoi proporre...',
    'collab.inviteArtists': 'Invita Artisti',
    'collab.searchPlaceholder': 'Cerca artisti da invitare...',
    'collab.invitedArtists': 'Artisti Invitati',
    'collab.cancel': 'Annulla',
    'collab.creating': 'Creazione...',
    'collab.create': 'Crea Collaborazione',

    // Messages
    'messages.title': 'Messaggi',
    'messages.searchPlaceholder': 'Cerca conversazioni...',
    'messages.loading': 'Caricamento messaggi...',
    'messages.empty': 'Nessuna conversazione',
    'messages.openMinichat': 'Apri minichat',

    // Minichat
    'minichat.open': 'Apri chat rapida',
    'minichat.title': 'Chat Rapide',
    'minichat.loading': 'Caricamento...',
    'minichat.empty': 'Nessuna conversazione. Inizia una chat dalla pagina Messaggi!',

    // Events (list)
    'events.pageTitle': 'Eventi',
    'events.pageSubtitle': 'Gestisci i tuoi eventi e opportunità',
    'events.createCta': 'Crea Evento',
    'events.empty': 'Nessun evento trovato',
    'events.detail': 'Dettagli',
    'events.participate': 'Partecipa',
    'events.loadingPage': 'Caricamento eventi...',
    'events.participantsCount': 'partecipanti',
    'events.loadingSingle': 'Caricamento evento...',
    'events.notFound': 'Evento non trovato',
    'events.back': 'Indietro',
    'events.backToEvent': "Torna all'Evento",
    'events.description': 'Descrizione',
    'events.startDate': 'Data Inizio',
    'events.endDate': 'Data Fine',
    'events.address': 'Indirizzo',
    'events.city': 'Città',
    'events.country': 'Paese',
    'events.requirements': 'Requisiti',
    'events.compensation': 'Compenso',
    'events.maxParticipants': 'Max Partecipanti',
    'events.manageParticipants': 'Gestisci Partecipanti',
    'events.pending': 'In Attesa',
    'events.accepted': 'Accettati',
    'events.rejected': 'Rifiutati',
    'events.accept': 'Accetta',
    'events.reject': 'Rifiuta',
    'events.create.title': 'Crea Evento',
    'events.create.subtitle': 'Crea un nuovo evento o opportunità',
    'events.create.baseInfo': 'Informazioni Base',
    'events.create.baseInfoDesc': "Dettagli principali dell'evento",
    'events.create.location': 'Posizione',
    'events.create.dateTime': 'Data e Ora',
    'events.create.extraDetails': 'Dettagli Aggiuntivi',
    'events.create.type': 'Tipo',
    'events.create.type.event': 'Evento',
    'events.create.type.job': 'Lavoro',
    'events.create.type.collaboration': 'Collaborazione',
    'events.create.type.training': 'Formazione',
    'events.create.startDateTime': 'Data/Ora Inizio',
    'events.create.endDateTime': 'Data/Ora Fine',
    'events.create.successTitle': 'Successo',
    'events.create.successDesc': 'Evento creato con successo',
    'events.create.errorTitle': 'Errore',
    'events.create.errorDefault': "Errore nella creazione dell'evento",

    // Quests
    'quests.title': 'Missioni',
    'quests.subtitle': 'Completa le missioni per guadagnare esperienza e aumentare la tua reputazione',
    'quests.loading': 'Caricamento missioni...',
    'quests.stats.completed': 'Completate',
    'quests.stats.active': 'In Corso',
    'quests.stats.available': 'Disponibili',
    'quests.activeTitle': 'Missioni in Corso',
    'quests.progress': 'Progresso',
  },
  en: {
    // Common
    'common.welcome': 'Welcome',
    'common.login': 'Login',
    'common.register': 'Register',
    'common.logout': 'Logout',
    'common.email': 'Email',
    'common.password': 'Password',
    'common.name': 'Name',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.search': 'Search',
    'common.loading': 'Loading...',
    'common.settings': 'Settings',
    'common.toggleLanguage': 'Toggle language',
    'common.myAccount': 'My account',
    'common.profile': 'Profile',
    
    // Login
    'login.identifierPlaceholder': 'email@example.com or nickname',
    'login.passwordPlaceholder': '••••••••',

    // Standalone Login/Register pages
    'auth.login.title': 'Sign in to Vybes',
    'auth.login.subtitle': 'Manage your account, notifications, posts and more.',
    'auth.login.emailLabel': 'Email',
    'auth.login.emailPlaceholder': 'Enter your email',
    'auth.login.passwordLabel': 'Password',
    'auth.login.passwordPlaceholder': 'Enter your password',
    'auth.login.forgotPassword': 'Forgot your password?',
    'auth.login.identifierLabel': 'Email or username',
    'auth.login.submitting': 'Signing in...',
    'auth.login.submit': 'SIGN IN',
    'auth.login.noAccount': 'Don’t have an account yet?',
    'auth.login.goRegister': 'REGISTER',

    'auth.register.title': 'Create your account',
    'auth.register.subtitle': 'Join the artistic community',
    'auth.register.nameLabel': 'Name',
    'auth.register.namePlaceholder': 'Your name',
    'auth.register.emailLabel': 'Email',
    'auth.register.emailPlaceholder': 'name@example.com',
    'auth.register.roleLabel': 'Role',
    'auth.register.role.viewer': 'Viewer',
    'auth.register.role.artist': 'Artist',
    'auth.register.role.recruiter': 'Recruiter',
    'auth.register.passwordLabel': 'Password',
    'auth.register.passwordConfirmLabel': 'Confirm password',
    'auth.register.passwordPlaceholder': 'Enter a strong password',
    'auth.register.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.register.submitting': 'Registering...',
    'auth.register.submit': 'REGISTER',

    // Auth page (single entrypoint)
    'auth.hero.description': 'Join the most vibrant community. Connect artists, recruiters, and culture lovers in one platform.',
    'auth.feature.portfolio': 'Portfolio',
    'auth.feature.map': 'Map',
    'auth.feature.chat': 'Chat',
    'auth.feature.gamification': 'Gamification',
    'auth.cta.login': 'Sign in',
    'auth.cta.register': 'Register',
    'auth.stats.artists': 'Artists',
    'auth.stats.events': 'Events',
    'auth.stats.recruiters': 'Recruiters',
    'auth.stats.cities': 'Cities',
    
    // Landing
    'landing.hero.title': 'The Platform for Artistic Culture',
    'landing.hero.subtitle': 'Connect artists, recruiters and enthusiasts in a single creative space',
    'landing.hero.cta': 'Get Started',
    'landing.hero.slogan.are': 'ARE',
    'landing.hero.slogan.you': 'YOU',
    'landing.hero.slogan.readyToMakeSome': 'READY TO MAKE SOME',
    'landing.hero.slogan.noise': 'NOISE',
    'landing.hero.cta.letsGo': 'Let’s go!',
    'landing.loginAttempt.title': 'Login attempt',
    'landing.loginAttempt.desc': 'Checking credentials...',
    'landing.login.title': 'Sign in to Vybes',
    'landing.login.subtitle': 'Manage your account, notifications, posts and more.',
    'landing.login.emailLabel': 'Email',
    'landing.login.emailPlaceholder': 'name@example.com',
    'landing.login.passwordLabel': 'Password',
    'landing.login.passwordPlaceholder': 'Enter your password',
    'landing.login.forgotPassword': 'Forgot your password?',
    'landing.login.submit': 'SIGN IN',
    'landing.login.submitting': 'Signing in...',
    'landing.login.noAccount': 'Don’t have an account yet?',
    'landing.login.goRegister': 'REGISTER',
    'landing.register.roles.title': 'Which roles do you want?',
    'landing.register.roles.subtitle': 'You can choose one or both roles.',
    'landing.register.role.artist': 'Artist',
    'landing.register.role.recruiter': 'Recruiter',
    'landing.register.selected': 'You selected:',
    'landing.register.selected.artist': '🎤 Artist',
    'landing.register.selected.recruiter': '🎭 Recruiter',
    'landing.register.field.firstName': 'First name',
    'landing.register.field.lastName': 'Last name',
    'landing.register.field.birthDate': 'Birth date',
    'landing.register.field.email': 'Email',
    'landing.register.field.emailConfirm': 'Confirm email',
    'landing.register.field.username': 'Username',
    'landing.register.field.password': 'Password',
    'landing.register.field.passwordConfirm': 'Confirm password',
    'landing.register.field.artistName': 'Stage name',
    'landing.register.field.recruiterType': 'Recruiter type',
    'landing.register.recruiterType.placeholder': 'Select type...',
    'landing.register.recruiterType.private': 'Private',
    'landing.register.recruiterType.company': 'Company',
    'landing.register.submit': 'REGISTER',
    'landing.register.submitting': 'Registering...',
    'landing.register.backToLogin': '← Back to login',

    // Validation (Landing register)
    'validation.firstNameRequired': 'First name is required.',
    'validation.lastNameRequired': 'Last name is required.',
    'validation.birthDateRequired': 'Birth date is required.',
    'validation.emailRequired': 'Email and confirmation are required.',
    'validation.emailsMismatch': 'Emails do not match.',
    'validation.usernameRequired': 'Username is required.',
    'validation.usernameInvalid': 'Invalid username.',
    'validation.passwordRequired': 'Password and confirmation are required.',
    'validation.passwordsMismatch': 'Passwords do not match.',
    'validation.passwordTooShort': 'Password is too short.',
    'validation.roleRequired': 'Select at least one role.',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.feed': 'Feed',
    'dashboard.map': 'Map',
    'dashboard.profile': 'Profile',
    'dashboard.events': 'Events',
    'dashboard.messages': 'Messages',
    'dashboard.portfolio': 'Portfolio',
    'dashboard.quests': 'Quests',
    'dashboard.minigames': 'Minigames',
    
    // Events
    'events.title': 'Events',
    'events.create': 'Create Event',
    'events.upcoming': 'Upcoming',
    'events.active': 'Active',
    'events.completed': 'Completed',
    'events.saved': 'Saved',
    
    // Profile
    'profile.level': 'Level',
    'profile.reputation': 'Reputation',
    'profile.experience': 'Experience',
    'profile.followers': 'Followers',
    'profile.following': 'Following',
    
    // Settings
    'settings.title': 'Settings',
    'settings.description': 'Manage your preferences and configurations',
    'settings.profile.title': 'Profile Information',
    'settings.profile.description': 'Edit your personal and biographical information',
    'settings.profile.name': 'Full Name',
    'settings.profile.username': 'Username',
    'settings.profile.email': 'Email',
    'settings.profile.emailNote': 'Email cannot be changed',
    'settings.profile.bio': 'Bio',
    'settings.profile.bioPlaceholder': 'Tell us something about yourself...',
    'settings.profile.location': 'Location',
    'settings.profile.locationPlaceholder': 'Your city or country',
    'settings.profile.website': 'Website / Link',
    'settings.profile.websitePlaceholder': 'https://...',
    'settings.profile.websiteNote': 'Link to your website, portfolio or social media',
    'settings.profile.uploadImage': 'Upload Image',
    'settings.profile.save': 'Save Changes',
    'settings.profile.saving': 'Saving...',
    'settings.profile.imageTypes': 'JPG, PNG or GIF. Max 5MB',
    'settings.appearance.title': 'Appearance',
    'settings.appearance.description': 'Customize the application appearance',
    'settings.appearance.theme': 'Theme',
    'settings.appearance.themeDesc': 'Switch between light and dark theme',
    'settings.appearance.language': 'Language',
    'settings.appearance.languageDesc': 'Select the interface language',
    'settings.notifications.title': 'Notifications',
    'settings.notifications.description': 'Manage your notification preferences',
    'settings.notifications.email': 'Email Notifications',
    'settings.notifications.emailDesc': 'Receive email notifications',
    'settings.notifications.push': 'Push Notifications',
    'settings.notifications.pushDesc': 'Receive push notifications in browser',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.empty': 'No notifications',
    'notifications.viewAll': 'View all notifications',
    'settings.account.title': 'Account',
    'settings.account.description': 'Manage your account information',
    'settings.account.changePassword': 'Change Password',
    'settings.account.deleteAccount': 'Delete Account',
    'settings.roles.title': 'Role Management',
    'settings.roles.description': 'Add or remove roles from your account',
    'settings.roles.artist': 'Artist',
    'settings.roles.recruiter': 'Recruiter',
    'settings.roles.addArtist': '+ Add Artist',
    'settings.roles.addRecruiter': '+ Add Recruiter',
    'settings.roles.active': 'Active roles',
    
    // Profile
    'profile.edit': 'Edit Profile',
    'profile.edit.subtitle': 'Update your personal information',
    'profile.edit.uploadHint': 'Click the icon to upload a new image',
    'profile.edit.profileLinkHint': 'Used for your profile link:',
    'profile.follow': 'Follow',
    'profile.unfollow': 'Unfollow',
    'profile.stats': 'Statistics',
    'profile.portfolio': 'Portfolio',
    'profile.portfolio.empty': 'Portfolio is empty',
    'profile.portfolio.addFirst': 'Add your first artwork',
    'profile.portfolio.add': 'Add Artwork',
    'profile.events.title': 'My Events',
    'profile.events.description': 'Manage your events and participations',
    'profile.events.create': 'Create Event',
    'profile.events.completed': 'Completed',
    'profile.events.ongoing': 'Ongoing',
    'profile.events.saved': 'Saved',
    'profile.events.created': 'Created',
    'profile.avatar.title': 'Customize Avatar',
    'profile.avatar.description': 'Customize your 3D avatar with outfits and accessories',
    'profile.avatar.open': 'Open Fitting Room',
    
    // Portfolio
    'portfolio.title': 'Portfolio',
    'portfolio.description': 'Show your art to the world',
    'portfolio.add': 'Add Artwork',
    'portfolio.empty': 'Your portfolio is empty',
    'portfolio.loading': 'Loading portfolio...',
    'portfolio.onlyArtists': 'This section is only available for artists',
    'portfolio.create.title': 'Add to portfolio',
    'portfolio.create.subtitle': 'Share your artworks with the community',
    'portfolio.create.fileUploadError': 'Error uploading file',
    'portfolio.create.createError': 'Error creating portfolio item',
    'portfolio.create.retry': 'Error creating portfolio item. Please try again.',
    'portfolio.create.onlyArtists': 'Only artists can add to the portfolio',
    'portfolio.create.back': 'Back',
    'portfolio.create.titleLabel': 'Title',
    'portfolio.create.titlePlaceholder': 'Artwork title',
    'portfolio.create.descriptionLabel': 'Description',
    'portfolio.create.descriptionPlaceholder': 'Describe your work...',
    'portfolio.create.typeLabel': 'Type',
    
    // Events
    'events.loading': 'Loading events...',
    'events.noCompleted': 'No completed events',
    'events.noOngoing': 'No ongoing events',
    'events.noSaved': 'No saved events',
    'events.noCreated': 'No created events',
    'events.participants': 'participants',
    
    // Common placeholders
    'placeholder.search': 'Search users, posts, events...',
    'placeholder.comment': 'Write a comment...',
    'placeholder.post': 'What do you want to share?',
    'placeholder.searchMap': 'Search artist, city, opportunity...',
    'placeholder.title': 'Title',
    'placeholder.description': 'Description',
    'placeholder.city': 'City',
    'placeholder.location': 'Location or address',
    'placeholder.latitude': 'Latitude',
    'placeholder.longitude': 'Longitude',
    
    // Toast messages
    'toast.success': 'Success',
    'toast.error': 'Error',
    'toast.emailVerified': 'Email verified',
    'toast.emailVerifiedDesc': 'You can now access your account',
    'toast.verifyError': 'Verification error',
    'toast.invalidToken': 'Invalid verification token',
    'toast.expiredToken': 'Verification token expired',
    'toast.verifyGenericError': 'Error during verification',
    'toast.eventCreated': 'Event created successfully',
    'toast.eventCreateError': 'Error creating event',
    'toast.markerCreated': 'Marker created successfully',
    'toast.markerCreateError': 'Error creating marker',
    'toast.profileUpdated': 'Profile updated successfully',
    'toast.profileUpdateError': 'Error updating profile',
    'toast.roleAdded': 'Role added',
    'toast.roleAddedDesc': 'Role added successfully',
    'toast.loading': 'Loading...',
    'toast.imageUploaded': 'Image uploaded',
    'toast.imageUploadSuccess': 'Image uploaded successfully',
    'toast.imageUploadError': 'Error uploading image',
    'toast.imageTypeError': 'File must be an image',
    'toast.imageSizeError': 'Image must not exceed 5MB',
    'toast.roleAddError': 'Error adding role',
    'toast.loginSuccess': 'Login successful',
    'toast.loginError': 'Login error',
    'toast.genericError': 'General error',
    'toast.validationError': 'Validation error',
    'toast.serverError': 'Server error',
    'toast.registrationAttempt': 'Registration attempt',
    'toast.registrationSuccess': 'Registration completed',
    'toast.registrationError': 'Registration error',
    'toast.purchaseSuccess': 'Purchase completed',
    'toast.purchaseError': 'Purchase error',
    'toast.avatarSaved': 'Avatar saved',
    'toast.avatarError': 'Error saving avatar',
    'toast.quizCompleted': 'Quiz completed!',
    'toast.loginRedirect': 'Redirecting to dashboard...',
    'toast.invalidCredentials': 'Incorrect email or password, or email not verified',
    'toast.registrationSending': 'Sending data to server...',
    'toast.checkEmail': 'Check your email to confirm your account',
    'toast.passwordMismatch': 'Passwords do not match',
    'toast.passwordTooShort': 'Password must be at least 8 characters',
    'toast.validationOk': 'Validation OK',
    'toast.formValid': 'Form valid, sending request...',
    'toast.wheelError': 'Error spinning the wheel',
    'toast.wheelWarning': 'Warning',
    'toast.quizUnlockOutfit': 'You unlocked a new outfit in the fitting room!',
    'toast.avatarConfigSaved': 'Your avatar configuration has been saved',
    'toast.avatarSaveError': 'Error saving',
    
    // Avatar
    'avatar.itemNotOwned': 'You must purchase this item before using it',
    'avatar.category.face': 'Face',
    'avatar.category.eyes': 'Eyes',
    'avatar.category.hair': 'Hair',
    'avatar.category.top': 'Top',
    'avatar.category.bottom': 'Bottoms',
    'avatar.category.accessories': 'Accessories',
    'avatar.previewTitle': 'Avatar preview',
    'avatar.preview3d': '3D avatar preview',
    'avatar.preview3dNote': '(3D render to be implemented)',
    'avatar.useAvatarInstead': 'Use avatar instead of profile image',
    'avatar.saving': 'Saving...',
    'avatar.saveConfig': 'Save configuration',
    'avatar.customizeTitle': 'Customize avatar',
    'avatar.currentlySelected': 'Currently selected',
    'common.active': 'Active',
    'common.inactive': 'Inactive',
    'toast.itemNotOwned': 'Item not owned',
    'avatar.purchaseSuccess': 'Purchase completed',
    'avatar.purchaseSuccessDesc': 'Item purchased successfully!',
    'avatar.purchaseError': 'Error during purchase',
    
    // Map
    'map.loading': 'Loading map...',
    'map.newAnnouncement': 'New Announcement',
    'map.newMarker': 'New Marker',
    'map.newMarkerShort': 'New',
    'map.artists': 'Artists',
    'map.opportunities': 'Opportunities',
    'map.all': 'All',
    'map.new': 'New',
    'map.search': 'Search',
    'map.filter': 'Filter',
    'map.filter.artists': 'Artists',
    'map.filter.opportunity': 'Opportunities',
    'map.createAnnouncement': 'Create Announcement',
    'map.opportunity': 'Opportunity',
    'map.collaboration': 'Collaboration',
    'map.clickToAdd': 'Click on the map to add a marker',
    'map.searchPlace': 'Search for a place',
    'map.selectPlace': 'Select a place from search',
    'map.selectLocation': 'Selected location',
    'map.latitude': 'Latitude',
    'map.longitude': 'Longitude',
    'map.candidate': 'Apply',
    'map.contact': 'Contact',
    'map.organizer': 'Organizer',
    'map.noResults': 'No results found',
    'map.enterLocation': 'Enter a location',
    'map.detail.apply': 'Apply',
    'map.detail.contact': 'Contact',
    'map.searchPlaceholder': 'Search place, city, artist...',
    'map.marker.typeOpportunity': 'Opportunity',
    'map.marker.typeCollaboration': 'Collaboration',
    'map.marker.create': 'Create Marker',
    
    // Search
    'search.users': 'Users',
    'search.posts': 'Posts',
    'search.events': 'Events',
    'search.user': 'User',
    'search.noResults': 'No results found',
    'search.loading': 'Loading...',
    'search.like': 'likes',
    'search.comments': 'comments',

    // Feed
    'feed.comments.empty': 'No comments yet. Be the first to comment!',
    'feed.newPost.title': 'New post',
    'feed.newPost.fileLabel': 'File',
    'feed.newPost.tags': 'Tags',
    'feed.newPost.cancel': 'Cancel',
    'feed.newPost.publish': 'Publish',
    'feed.newPost.publishing': 'Publishing...',
    'feed.newPost.uploadError': 'Error uploading file',
    'feed.newPost.retry': 'Error publishing post. Please try again.',

    // Collaboration post
    'collab.title': 'Create collaboration',
    'collab.descriptionLabel': 'Collaboration description',
    'collab.descriptionPlaceholder': 'Describe the collaboration you want to propose...',
    'collab.inviteArtists': 'Invite artists',
    'collab.searchPlaceholder': 'Search artists to invite...',
    'collab.invitedArtists': 'Invited artists',
    'collab.cancel': 'Cancel',
    'collab.creating': 'Creating...',
    'collab.create': 'Create collaboration',

    // Messages
    'messages.title': 'Messages',
    'messages.searchPlaceholder': 'Search conversations...',
    'messages.loading': 'Loading messages...',
    'messages.empty': 'No conversations',
    'messages.openMinichat': 'Open minichat',

    // Minichat
    'minichat.open': 'Open quick chat',
    'minichat.title': 'Quick Chats',
    'minichat.loading': 'Loading...',
    'minichat.empty': 'No conversations. Start a chat from the Messages page!',

    // Events (list)
    'events.pageTitle': 'Events',
    'events.pageSubtitle': 'Manage your events and opportunities',
    'events.createCta': 'Create Event',
    'events.empty': 'No events found',
    'events.detail': 'Details',
    'events.participate': 'Participate',
    'events.loadingPage': 'Loading events...',
    'events.participantsCount': 'participants',
    'events.loadingSingle': 'Loading event...',
    'events.notFound': 'Event not found',
    'events.back': 'Back',
    'events.backToEvent': 'Back to event',
    'events.description': 'Description',
    'events.startDate': 'Start date',
    'events.endDate': 'End date',
    'events.address': 'Address',
    'events.city': 'City',
    'events.country': 'Country',
    'events.requirements': 'Requirements',
    'events.compensation': 'Compensation',
    'events.maxParticipants': 'Max participants',
    'events.manageParticipants': 'Manage participants',
    'events.pending': 'Pending',
    'events.accepted': 'Accepted',
    'events.rejected': 'Rejected',
    'events.accept': 'Accept',
    'events.reject': 'Reject',
    'events.create.title': 'Create event',
    'events.create.subtitle': 'Create a new event or opportunity',
    'events.create.baseInfo': 'Basic info',
    'events.create.baseInfoDesc': 'Main event details',
    'events.create.location': 'Location',
    'events.create.dateTime': 'Date & time',
    'events.create.extraDetails': 'Additional details',
    'events.create.type': 'Type',
    'events.create.type.event': 'Event',
    'events.create.type.job': 'Job',
    'events.create.type.collaboration': 'Collaboration',
    'events.create.type.training': 'Training',
    'events.create.startDateTime': 'Start date/time',
    'events.create.endDateTime': 'End date/time',
    'events.create.successTitle': 'Success',
    'events.create.successDesc': 'Event created successfully',
    'events.create.errorTitle': 'Error',
    'events.create.errorDefault': 'Error creating event',

    // Quests
    'quests.title': 'Quests',
    'quests.subtitle': 'Complete quests to earn XP and increase your reputation',
    'quests.loading': 'Loading quests...',
    'quests.stats.completed': 'Completed',
    'quests.stats.active': 'Active',
    'quests.stats.available': 'Available',
    'quests.activeTitle': 'Active Quests',
    'quests.progress': 'Progress',
  },
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>('it')

  useEffect(() => {
    const saved = localStorage.getItem('language') as Language
    if (saved && (saved === 'it' || saved === 'en')) {
      setLanguage(saved)
    }
  }, [])

  useEffect(() => {
    // Keep <html lang="..."> in sync for accessibility/SEO.
    if (typeof document !== 'undefined') {
      document.documentElement.lang = language
    }
  }, [language])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['it']] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

